### PR TITLE
Api v2 support

### PR DESCRIPTION
**Pull request by shortdudey123**
Commits are from https://github.com/sqm/pager_duty-connection/commits/master

Closes https://github.com/technicalpickles/pager_duty-connection/issues/20

### CODE REVIEW

**Comment by nubecoder** [comment]
v1 EOL is July 6th 2017.
What's the holdup getting this v2 support merged in?

**Comment by technicalpickles** [comment]
I'm not actively using this library, so I can merge & release this, but I can't really provide much quality control on it without using it somewhere.

**Comment by keiththomps** [comment]
@amandapuff and I were originally going to wait and clean things up before submitting a PR for this, but neither of us got around to it. That being said we've been using this in production since October.

**Comment by technicalpickles** [comment]
I just released 1.0.0 with this PR. Thanks for the contribution, and sorry it took so long to get to 😅

**Comment by nubecoder** [comment]
Thanks to everyone involved.

**Pull request merged**
